### ISSUE TITLE
Starlite Integration

### ISSUE THREAD

**Issue by Goldziher** [keithasaurus/koda-validate#28]
Hi there @keithasaurus,

Impressive library! I wonder whether you'd like exploring integrating it into [Starlite](https://github.com/starlite-api/starlite)? We are working on v2 now and aim to release it in soonish. As part of this effort we would like to have an alternative to pydantic in place - and this lib looks like an option. If its something that can interest you, lemme know.

**Comment by keithasaurus** [comment]
@Goldziher Yes, sounds good. I'll contact through email.

**Comment by Goldziher** [comment]
Hi, i didn't get a mail. 

Wanna join our discord?
