### ISSUE TITLE
Generate a JSON schema

### ISSUE THREAD

**Issue by cbenz** [keithasaurus/koda-validate#34]
Hi! I'd like to know if it would be possible to generate a [JSON schema](https://json-schema.org/) from validators.

This would allow, for example, enhancing UX in an IDE when editing JSON files by adding auto-completion.
For instance, VSCode supports associating a JSON Schema to a file (cf [docs](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings) or [this blog article](https://frontaid.io/blog/json-schema-vscode/)).

I don't know the feasibility or complexity.

**Comment by keithasaurus** [comment]
I think what you're after is already implemented in the serialization package: https://koda-validate.readthedocs.io/en/stable/api/koda_validate.serialization.html. You can also see how some of the functions are used in tests here: https://github.com/keithasaurus/koda-validate/blob/b0fd1121ce82c1a3e1267e46327836ac24d5cd29/tests/test_serialization/test_json_schema.py
